# A.3 브로드캐스팅

In [57]:
# 브로드캐스팅은 다른 모양의 배열 간의 산술 연산을 어떻게 수행해야 하는지 설명한다.
# 이는 매우 강력한 기능이지만 NumPy의 오랜 사용자들도 흔히 잘못 이해하고 있는 기능이다.
# 브로드캐스팅의 가장 단순한 예제는 하나의 배열에서 스칼라값을 합칠 때 발생한다.

In [58]:
import numpy as np
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [59]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [60]:
# 여기서 스칼라값 4는 곱셈 연산 과정에서 배열의 모든 원소로 브로드캐스트되었다.

In [61]:
# 예를 들어 배열의 각 컬럼에서 컬럼 평균값을 뺀다면 다음처럼 간단하게 처리할 수 있다.

In [62]:
arr = np.random.randn(4, 3)

In [63]:
arr.mean(0)

array([-0.34662771,  0.52552733,  0.26415755])

In [64]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 1.29224759, -1.04475255, -0.3681476 ],
       [-1.48485278, -0.29797197,  0.82057165],
       [ 0.04216817,  0.78499757,  0.92131978],
       [ 0.15043702,  0.55772695, -1.37374383]])

In [65]:
demeaned.mean(0)

array([-2.77555756e-17, -5.55111512e-17,  5.55111512e-17])

In [66]:
# [그림 A-4]는 이 과정을 묘사하고 있다. 위 브로드캐스팅 연산을 로우에 대해 수행한다면 좀 더 주의를 기울여야 한다. 페이지 602
# 다행히도 브로드캐스팅 규칙을 따르기만 한다면 잠재적으로 낮은 차원의 값을 배열의 다른 차원으로 브로드캐스팅하는 것도 가능하다.

- 브로드캐스팅 규칙
    - 만일 이어지는 각 차원(시작부터 끝까지)에 대해 축의 길이가 일치하거나 둘 중 하나의 길이가 1이라면 두 배열은 호환이다.
    - 브로드캐스팅은 누락된, 혹은 길이가 1인 차원에 대해 수행된다.

In [67]:
# 이전 예제에서 컬럼이 아니라 각 로우에서 평균값을 뺀다고 가정해보자.
# arr.mean(0)은 길이가 3이고 arr의 이어지는 크기 역시 3이므로 0번 축에 대해 브로드캐스팅이 가능하다.
# 브로드캐스팅 규칙에 따르면 1번 축에 대해 뺄셈을 하려면(각 로우에서 로우 평균값을 빼려면) 작은 크기의 배열은 (4, 1)의 크기를 가져야 한다.

In [68]:
arr

array([[ 0.94561988, -0.51922522, -0.10399004],
       [-1.83148049,  0.22755536,  1.08472921],
       [-0.30445954,  1.3105249 ,  1.18547733],
       [-0.19619069,  1.08325428, -1.10958628]])

In [69]:
row_means = arr.mean(1)

In [70]:
row_means.shape

(4,)

In [71]:
row_means.reshape((4, 1))

array([[ 0.10746821],
       [-0.17306531],
       [ 0.73051423],
       [-0.07417423]])

In [72]:
demeaned = arr - row_means.reshape((4, 1))

In [73]:
demeaned.mean(1)

array([-1.85037171e-17, -7.40148683e-17, -7.40148683e-17, -7.40148683e-17])

In [74]:
# 이 과정을 묘사한 [그림 A-5]를 참조하자. 페이지 603

In [75]:
# [그림 A-6]은 3차원 배열의 0번 축에 대해 2차원 배열의 값을 더하는 과정을 나타내고 있다. 페이지 603

# A.3.1 다른 축에 대해 브로드캐스팅하기

In [76]:
# 다차원 배열에서의 브로드캐스팅은 정말 머리에 쥐가 나는 작업이지만 규칙을 잘 따르기만 하면 된다.
# 그렇지 않으면 다음과 같은 에어를 만나게 될 것이다.

In [77]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [78]:
# 0번 축이 아닌 다른 축에 대해 낮은 차원의 배열로 산술 연산을 수행하는 일은 흔히 생길 수 있다.
# 브로드캐스팅 규칙을 따르자면 "브로드캐스트 차원"은 작은 배열에서는 반드시 1이어야 한다.
# 로우에서 평균값을 빼는 앞의 예제에서 로우 평균은 (4, )가 아니라 (4, 1)로 재형성한다는 의미다.

In [79]:
arr - arr.mean(1).reshape((4, 1))

array([[ 0.83815167, -0.62669343, -0.21145825],
       [-1.65841518,  0.40062067,  1.25779451],
       [-1.03497377,  0.58001067,  0.4549631 ],
       [-0.12201646,  1.15742851, -1.03541205]])

In [80]:
# 3차원의 경우 세 가지 차원 중 어느 하나에 대한 브로드캐스팅은 데이터를 호환되는 모양으로 재형성하면 된다.
# [그림 A-7]에 3차원 배열의 각 축에 대해 브로드캐스팅하기 위해 필요한 2차원 배열의 모습을 잘 묘사해놓았다. 페이지 605

In [81]:
# 따라서 아주 일반적인 문제는 브로드캐스팅 전용 목적으로 길이가 1인 새로운 축을 추가하는 것이다.
# reshape를 사용하는 것도 한 방법이지만 축을 하나 새로 추가하는 것은 새로운 모양을 나타낼 튜플을 하나 생성해야 한다.
# NumPy 배열은 색인을 통해 새로운 축을 추가하는 특수한 문법을 제공한다.
# np.newaxis라는 이 특수한 속성을 배열의 전체 슬라이스와 함께 사용해서 새로운 축을 추가할 수 있다.

In [82]:
arr = np.zeros((4, 4))

In [83]:
arr_3d = arr[:, np.newaxis, :]

In [84]:
arr_3d.shape

(4, 1, 4)

In [85]:
arr_1d = np.random.normal(size=3)

In [86]:
arr_1d[:, np.newaxis]

array([[-1.34535327],
       [-0.31864597],
       [-0.17239563]])

In [87]:
arr_1d[np.newaxis, :]

array([[-1.34535327, -0.31864597, -0.17239563]])

In [88]:
# 그러므로 만약 3차원 배열에서 2번 축에 대해 평균값을 빼고 싶다면 다음과 같이 작성하면 된다.

In [89]:
arr = np.random.randn(3, 4, 5)

In [90]:
depth_means = arr.mean(2)

In [91]:
depth_means

array([[-0.28038088, -0.63286628,  0.12559449, -0.15992668],
       [-0.13984432, -0.5889194 ,  0.51176835,  0.96594639],
       [-0.2976438 ,  1.19834803, -0.07233314,  0.15050603]])

In [92]:
depth_means.shape

(3, 4)

In [93]:
demeaned = arr - depth_means[:, :, np.newaxis]

In [94]:
demeaned.mean(2)

array([[-1.11022302e-17,  0.00000000e+00,  2.22044605e-17,
         0.00000000e+00],
       [ 2.22044605e-17, -4.44089210e-17, -3.33066907e-17,
         1.33226763e-16],
       [ 1.11022302e-17, -2.66453526e-16,  0.00000000e+00,
        -8.88178420e-17]])

In [95]:
# 성능을 희생하지 않으면서 한 축에 대해 평균값을 빼는 과정을 일반화할 수 없을까?
# 사실 방법이 존재하긴 하지만 색인을 이용한 약간의 서커스가 필요하다.

In [96]:
def dmeans_axis(arr, axis=0):
    means = arr.mean(axis)
    
    # 이렇게 n차원에 대해서 [:, :, np.newaxis]를 수행하는 과정을 일반화할 수 있다.
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

# A.3.2 브로드캐스팅을 이용해서 배열에 값 대입하기

In [97]:
# 배열의 색인을 통해 값을 대입할 때도 산술 연산에서의 브로드캐스팅 규칙이 적용된다.
# 간단하게는 다음과 같이 할 수 있다.

In [98]:
arr = np.zeros((4, 3))

In [99]:
arr[:] = 5

In [100]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [101]:
# 하지만 만약 값이 담긴 1차원 배열이 있고 그 배열의 컬럼에 값을 대입하고 싶다면 배열의 모양이 호환되는 한 그렇게 하는 것이 가능하다.

In [102]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [104]:
arr[:] = col[:, np.newaxis]

In [105]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [106]:
arr[:2]

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42]])

In [107]:
arr[:2] = [[-1.37], [0.509]]

In [108]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])